# Generated by Django 3.0.2 on 2020-02-26 16:57

from django.db import migrations
from django.utils import timezone


def populate_db(apps, schema_editor):
    Comment = apps.get_model('blog', 'Comment')
    Blog = apps.get_model('blog', 'Blog')

    avril = Blog(title="There Was This Sk8ter Boi...", author="Avirl Lavigne",
                 content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate erat at lacus "
                         "consectetur, et venenatis ex egestas. Fusce vel tortor quam. Etiam eget aliquet metus. "
                         "Mauris cursus ante at nulla sodales ullamcorper. Nunc nec est vitae tellus pulvinar "
                         "fermentum et sed ex. Donec hendrerit tincidunt tellus, in porta ipsum vestibulum a. "
                         "Maecenas fermentum urna in quam tincidunt, et bibendum urna hendrerit. Curabitur dictum "
                         "tortor quis eros porttitor, et hendrerit lorem pulvinar. Vestibulum sit amet erat vel erat "
                         "porttitor ultrices vitae sit amet lorem. Vestibulum purus metus, condimentum in convallis "
                         "at, ornare eget ex. Suspendisse in risus nec lacus mollis tincidunt id non odio. Donec leo "
                         "diam, fringilla dapibus sagittis id, imperdiet quis odio. Orci varius natoque penatibus et "
                         "magnis dis parturient montes, nascetur ridiculus mus. Curabitur maximus velit tellus, "
                         "quis ultricies quam euismod a. Suspendisse maximus vel turpis vel lacinia. Duis ornare arcu "
                         "facilisis lectus scelerisque vulputate. Curabitur id est pellentesque, lobortis dui sed, "
                         "tempus sapien. Nam metus neque, placerat vitae nibh ut, efficitur egestas dui. Integer "
                         "porttitor lacus eu elementum facilisis. Donec porta eros pharetra, commodo felis sed, mattis "
                         "ligula. Nullam volutpat euismod turpis, ac luctus elit aliquet a. Morbi fringilla gravida "
                         "enim non mollis. Maecenas et nisi eget magna rhoncus sodales sit amet in lectus. Morbi "
                         "blandit enim ut purus mattis finibus. Cras elementum, massa eu tincidunt sodales, felis "
                         "tortor efficitur dolor, in fermentum eros tortor eu velit. Nullam vitae feugiat eros. "
                         "Vestibulum porta justo nec tincidunt volutpat. Maecenas vitae nisl scelerisque, ultricies "
                         "purus sit amet, consectetur elit. Sed purus libero, mollis ut euismod non, consequat ac "
                         "tellus. Quisque luctus arcu id augue pulvinar, sed rhoncus lacus laoreet. Integer tempor vel "
                         "lectus a lobortis. Nulla facilisi. Quisque mollis, quam sed ultricies gravida, arcu elit "
                         "rhoncus odio, pretium venenatis nisl arcu commodo magna. Vestibulum ante ipsum primis in "
                         "faucibus orci luctus et ultrices posuere cubilia Curae; Morbi at urna a sem commodo commodo "
                         "porttitor et ante. Curabitur consectetur nibh sapien, vitae vulputate quam congue a. Nunc "
                         "congue nisi id ornare iaculis. Praesent vulputate elit quis massa venenatis, eget vulputate "
                         "nunc tempus. Praesent in sapien blandit, fermentum ligula eget, varius urna.",
                 posted=timezone.now())
    avril.save()

    sk8ter_boi_comment = Comment(blog=avril, commenter="sk8ter boi", email="sk8terboi@gmail.com",
                                 content="Thanks for the Shout-out!", posted=timezone.now())
    sk8ter_boi_comment.save()

    gamer_girl_comment = Comment(blog=avril, commenter="Gamer Girl", email="GamerGirl@gmail.com",
                                 content="LOL, Stop kissing ***!", posted=timezone.now())
    gamer_girl_comment.save()

    gamer_girl = Blog(title="Why You Should Buy My Bathwater:", author="Gamer Girl",
                 content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate erat at lacus "
                         "consectetur, et venenatis ex egestas. Fusce vel tortor quam. Etiam eget aliquet metus. "
                         "Mauris cursus ante at nulla sodales ullamcorper. Nunc nec est vitae tellus pulvinar "
                         "fermentum et sed ex. Donec hendrerit tincidunt tellus, in porta ipsum vestibulum a. "
                         "Maecenas fermentum urna in quam tincidunt, et bibendum urna hendrerit. Curabitur dictum "
                         "tortor quis eros porttitor, et hendrerit lorem pulvinar. Vestibulum sit amet erat vel erat "
                         "porttitor ultrices vitae sit amet lorem. Vestibulum purus metus, condimentum in convallis "
                         "at, ornare eget ex. Suspendisse in risus nec lacus mollis tincidunt id non odio. Donec leo "
                         "diam, fringilla dapibus sagittis id, imperdiet quis odio. Orci varius natoque penatibus et "
                         "magnis dis parturient montes, nascetur ridiculus mus. Curabitur maximus velit tellus, "
                         "quis ultricies quam euismod a. Suspendisse maximus vel turpis vel lacinia. Duis ornare arcu "
                         "facilisis lectus scelerisque vulputate. Curabitur id est pellentesque, lobortis dui sed, "
                         "tempus sapien. Nam metus neque, placerat vitae nibh ut, efficitur egestas dui. Integer "
                         "porttitor lacus eu elementum facilisis. Donec porta eros pharetra, commodo felis sed, mattis "
                         "ligula. Nullam volutpat euismod turpis, ac luctus elit aliquet a. Morbi fringilla gravida "
                         "enim non mollis. Maecenas et nisi eget magna rhoncus sodales sit amet in lectus. Morbi "
                         "blandit enim ut purus mattis finibus. Cras elementum, massa eu tincidunt sodales, felis "
                         "tortor efficitur dolor, in fermentum eros tortor eu velit. Nullam vitae feugiat eros. "
                         "Vestibulum porta justo nec tincidunt volutpat. Maecenas vitae nisl scelerisque, ultricies "
                         "purus sit amet, consectetur elit. Sed purus libero, mollis ut euismod non, consequat ac "
                         "tellus. Quisque luctus arcu id augue pulvinar, sed rhoncus lacus laoreet. Integer tempor vel "
                         "lectus a lobortis. Nulla facilisi. Quisque mollis, quam sed ultricies gravida, arcu elit "
                         "rhoncus odio, pretium venenatis nisl arcu commodo magna. Vestibulum ante ipsum primis in "
                         "faucibus orci luctus et ultrices posuere cubilia Curae; Morbi at urna a sem commodo commodo "
                         "porttitor et ante. Curabitur consectetur nibh sapien, vitae vulputate quam congue a. Nunc "
                         "congue nisi id ornare iaculis. Praesent vulputate elit quis massa venenatis, eget vulputate "
                         "nunc tempus. Praesent in sapien blandit, fermentum ligula eget, varius urna.",
                      posted=timezone.now())
    gamer_girl.save()

    seems_like_a_scam = Comment(blog=gamer_girl, commenter="sk8ter boi", email="sk8terboi@gmail.com",
                                content="This looks like a scam to me...", posted=timezone.now())
    seems_like_a_scam.save()

    scam_agreement = Comment(blog=gamer_girl, commenter="Avril Lavigne", email="avrilLavigne@gmail.com",
                             content="I agree", posted=timezone.now())
    scam_agreement.save()

    sk8ter_boi = Blog(title="How I Rocked MTV!", author="sk8ter boi",
                 content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate erat at lacus "
                         "consectetur, et venenatis ex egestas. Fusce vel tortor quam. Etiam eget aliquet metus. "
                         "Mauris cursus ante at nulla sodales ullamcorper. Nunc nec est vitae tellus pulvinar "
                         "fermentum et sed ex. Donec hendrerit tincidunt tellus, in porta ipsum vestibulum a. "
                         "Maecenas fermentum urna in quam tincidunt, et bibendum urna hendrerit. Curabitur dictum "
                         "tortor quis eros porttitor, et hendrerit lorem pulvinar. Vestibulum sit amet erat vel erat "
                         "porttitor ultrices vitae sit amet lorem. Vestibulum purus metus, condimentum in convallis "
                         "at, ornare eget ex. Suspendisse in risus nec lacus mollis tincidunt id non odio. Donec leo "
                         "diam, fringilla dapibus sagittis id, imperdiet quis odio. Orci varius natoque penatibus et "
                         "magnis dis parturient montes, nascetur ridiculus mus. Curabitur maximus velit tellus, "
                         "quis ultricies quam euismod a. Suspendisse maximus vel turpis vel lacinia. Duis ornare arcu "
                         "facilisis lectus scelerisque vulputate. Curabitur id est pellentesque, lobortis dui sed, "
                         "tempus sapien. Nam metus neque, placerat vitae nibh ut, efficitur egestas dui. Integer "
                         "porttitor lacus eu elementum facilisis. Donec porta eros pharetra, commodo felis sed, mattis "
                         "ligula. Nullam volutpat euismod turpis, ac luctus elit aliquet a. Morbi fringilla gravida "
                         "enim non mollis. Maecenas et nisi eget magna rhoncus sodales sit amet in lectus. Morbi "
                         "blandit enim ut purus mattis finibus. Cras elementum, massa eu tincidunt sodales, felis "
                         "tortor efficitur dolor, in fermentum eros tortor eu velit. Nullam vitae feugiat eros. "
                         "Vestibulum porta justo nec tincidunt volutpat. Maecenas vitae nisl scelerisque, ultricies "
                         "purus sit amet, consectetur elit. Sed purus libero, mollis ut euismod non, consequat ac "
                         "tellus. Quisque luctus arcu id augue pulvinar, sed rhoncus lacus laoreet. Integer tempor vel "
                         "lectus a lobortis. Nulla facilisi. Quisque mollis, quam sed ultricies gravida, arcu elit "
                         "rhoncus odio, pretium venenatis nisl arcu commodo magna. Vestibulum ante ipsum primis in "
                         "faucibus orci luctus et ultrices posuere cubilia Curae; Morbi at urna a sem commodo commodo "
                         "porttitor et ante. Curabitur consectetur nibh sapien, vitae vulputate quam congue a. Nunc "
                         "congue nisi id ornare iaculis. Praesent vulputate elit quis massa venenatis, eget vulputate "
                         "nunc tempus. Praesent in sapien blandit, fermentum ligula eget, varius urna.",
                      posted=timezone.now())
    sk8ter_boi.save()

    happy_success = Comment(blog=sk8ter_boi, commenter="Anon", email="fakeEmail@gmail.com",
                            content="I am happy for your success.", posted=timezone.now())
    happy_success.save()

    anon = Blog(title="Potions & How to Brew Them", author="Anon",
                 content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate erat at lacus "
                         "consectetur, et venenatis ex egestas. Fusce vel tortor quam. Etiam eget aliquet metus. "
                         "Mauris cursus ante at nulla sodales ullamcorper. Nunc nec est vitae tellus pulvinar "
                         "fermentum et sed ex. Donec hendrerit tincidunt tellus, in porta ipsum vestibulum a. "
                         "Maecenas fermentum urna in quam tincidunt, et bibendum urna hendrerit. Curabitur dictum "
                         "tortor quis eros porttitor, et hendrerit lorem pulvinar. Vestibulum sit amet erat vel erat "
                         "porttitor ultrices vitae sit amet lorem. Vestibulum purus metus, condimentum in convallis "
                         "at, ornare eget ex. Suspendisse in risus nec lacus mollis tincidunt id non odio. Donec leo "
                         "diam, fringilla dapibus sagittis id, imperdiet quis odio. Orci varius natoque penatibus et "
                         "magnis dis parturient montes, nascetur ridiculus mus. Curabitur maximus velit tellus, "
                         "quis ultricies quam euismod a. Suspendisse maximus vel turpis vel lacinia. Duis ornare arcu "
                         "facilisis lectus scelerisque vulputate. Curabitur id est pellentesque, lobortis dui sed, "
                         "tempus sapien. Nam metus neque, placerat vitae nibh ut, efficitur egestas dui. Integer "
                         "porttitor lacus eu elementum facilisis. Donec porta eros pharetra, commodo felis sed, mattis "
                         "ligula. Nullam volutpat euismod turpis, ac luctus elit aliquet a. Morbi fringilla gravida "
                         "enim non mollis. Maecenas et nisi eget magna rhoncus sodales sit amet in lectus. Morbi "
                         "blandit enim ut purus mattis finibus. Cras elementum, massa eu tincidunt sodales, felis "
                         "tortor efficitur dolor, in fermentum eros tortor eu velit. Nullam vitae feugiat eros. "
                         "Vestibulum porta justo nec tincidunt volutpat. Maecenas vitae nisl scelerisque, ultricies "
                         "purus sit amet, consectetur elit. Sed purus libero, mollis ut euismod non, consequat ac "
                         "tellus. Quisque luctus arcu id augue pulvinar, sed rhoncus lacus laoreet. Integer tempor vel "
                         "lectus a lobortis. Nulla facilisi. Quisque mollis, quam sed ultricies gravida, arcu elit "
                         "rhoncus odio, pretium venenatis nisl arcu commodo magna. Vestibulum ante ipsum primis in "
                         "faucibus orci luctus et ultrices posuere cubilia Curae; Morbi at urna a sem commodo commodo "
                         "porttitor et ante. Curabitur consectetur nibh sapien, vitae vulputate quam congue a. Nunc "
                         "congue nisi id ornare iaculis. Praesent vulputate elit quis massa venenatis, eget vulputate "
                         "nunc tempus. Praesent in sapien blandit, fermentum ligula eget, varius urna.",
                posted=timezone.now())
    anon.save()

    shameless_plug = Comment(blog=anon, commenter="Gamer Girl", email="GamerGirl@gmail.com",
                             content="Speaking of which, I am a GREAT alchemist; my bath-water by itself is considered "
                                     "magical! That's why you should sub to me on Patreon, and BUY MY BATHWATER!",
                             posted=timezone.now())
    shameless_plug.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200224_1548'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
