# Generated by Django 3.0.2 on 2020-02-26 16:39

from django.db import migrations
from django.utils import timezone


def populate_db(apps, schema_editor):
    Choice = apps.get_model('polls', 'Choice')
    Question = apps.get_model('polls', 'Question')

    pizza_q = Question(question_text="Best kind of pizza?", pub_date=timezone.now())
    pizza_q.save()

    pepperoni = Choice(question=pizza_q, choice_text="Carnivore", votes=27)
    pepperoni.save()

    hawaiian = Choice(question=pizza_q, choice_text="The Real Dill", votes=13)
    hawaiian.save()

    combination = Choice(question=pizza_q, choice_text="Marghie", votes=42)
    combination.save()

    meat_lovers = Choice(question=pizza_q, choice_text="Carmen", votes=78)
    meat_lovers.save()

    jamesbond_q = Question(question_text="Best James Bond Actor?", pub_date=timezone.now())
    jamesbond_q.save()

    sean = Choice(question=jamesbond_q, choice_text="Sean Connery", votes=92)
    sean.save()

    pierce = Choice(question=jamesbond_q, choice_text="Pierce Brosnan", votes=47)
    pierce.save()

    roger = Choice(question=jamesbond_q, choice_text="Roger Moore", votes=29)
    roger.save()

    daniel = Choice(question=jamesbond_q, choice_text="Daniel Craig", votes=44)
    daniel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
